language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update
  - sudo apt-get install -y check
before_script:
  - chmod +x autogen.sh
  - ./autogen.sh
script:
  - ./configure
  - make
  - make check
after_failure:
  - cat tests/test-suite.log
