language: c
compiler:
  - gcc
before_install:
  - sudo apt-get update
  - sudo apt-get install -y check
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov
before_script:
  - chmod +x autogen.sh
  - ./autogen.sh
script:
  - ./configure
  - make -C htslib
  - make -C bwa
  - make CFLAGS='-O0 --coverage'
  - make check CFLAGS='-O0 --coverage'
after_success:
  - lcov --directory . --capture --output-file cov.info
  - lcov --remove cov.info '*tests*' '*sqlite3*' '*log*' '*wrapper.c' '*db.c' -o cov.info
  - lcov --list cov.info
  - coveralls-lcov cov.info
after_failure:
  - cat tests/test-suite.log
