dist: bionic

language: c

compiler: gcc

addons:
  apt:
    packages:
      - check
      - ninja-build
      - python3-pip
      - python3-setuptools
      - valgrind

install:
  - pip3 install meson
  - pip3 install cpp-coveralls

env:
  - CK_DEFAULT_TIMEOUT=0

script:
  - meson -Db_coverage=true builddir
  - ninja -C builddir
  - meson test -C builddir
  - meson test -C builddir --wrap='valgrind --leak-check=full --error-exitcode=1' -t 3

after_success:
  - >
    coveralls
    --root .
    --build-root builddir
    --exclude builddir/meson-private
    --exclude subprojects
    --exclude tests
    --exclude src/log.c
    --exclude src/logger.c
    --exclude src/main.c
    --exclude src/make_vcf.c
    --exclude src/merge_call.c
    --exclude src/process_sample.c
    --exclude src/sam.c
    --exclude src/thpool.c
    --exclude-pattern '.+\.h$'
    --gcov-options '\-lp'

after_failure:
  - cat builddir/meson-logs/meson-log.txt
  - cat builddir/meson-logs/testlog.txt
  - cat builddir/meson-logs/testlog-valgrind.txt
